1) Create project folder
mkdir -p ~/jenkins-static-site
cd ~/jenkins-static-site

2) Create docker-compose.yml

Create a file docker-compose.yml with this content:

version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
    driver: local


Why /var/run/docker.sock?
Mounting the Docker socket lets Jenkins run Docker commands (so pipeline can build images or run containers). Security warning: this gives Jenkins root-like control over the host Docker daemon — see Security notes below.

3) Start Jenkins container
docker compose up -d


Check logs to confirm:

docker compose logs -f jenkins


Wait until logs show Jenkins is fully up and running (may take a few minutes on first start).

4) Get initial admin password
docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword


Copy that password.

Open your browser at: http://localhost:8080
Use the password to unlock Jenkins → choose Install suggested plugins → create an admin user when prompted.

5) Install HTML Publisher plugin

In Jenkins: Manage Jenkins → Manage Plugins → Available.

Search HTML Publisher.

Tick the plugin and click Install without restart (or install and restart if prompted).

Wait for installation to finish.

(Alternatively you can install via Manage Plugins → Advanced → Upload Plugin if you have .hpi file.)

6) Create the pipeline job (UI method)
A. Create new pipeline item

Jenkins → New Item → name: karunya-site-pipeline → Pipeline → OK.

B. Configure pipeline

Scroll to Pipeline section.

Definition: choose Pipeline script.

Paste the pipeline script below into the script box.

Save.

Pipeline script (copy & paste)
pipeline {
  agent any

  stages {
    stage('Generate site') {
      steps {
        script {
          sh 'rm -rf site || true'
          sh 'mkdir -p site/assets'

          writeFile file: 'site/index.html', text: """<!doctype html>
<html lang="en">
<head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Karunya University — Simple Site</title>
<link rel="stylesheet" href="assets/style.css"/>
</head><body>
<header class="site-header">
<div class="container">
<h1>Karunya University</h1>
<p class="tagline">Values — Knowledge — Service</p>
</div>
</header>
<main class="container">
<section class="card">
<h2>About Karunya University</h2>
<p>Karunya Institute of Technology and Sciences is a leading centre for higher education in India.</p>
</section>
</main>
<footer class="site-footer container">
<p>&copy; ${new Date().format('yyyy')} Karunya University — Generated by Jenkins</p>
</footer>
</body>
</html>"""

          writeFile file: 'site/assets/style.css', text: """body { font-family: Arial, sans-serif; margin:0; }
.container { max-width:800px; margin:0 auto; padding:20px; }
.site-header { background:#0b3d91; color:#fff; padding:20px; }
.tagline { font-size:14px; opacity:0.8; }
.card { background:#fff; border:1px solid #ddd; padding:15px; margin:15px 0; border-radius:6px; }
.site-footer { text-align:center; font-size:12px; color:#555; margin-top:20px; }"""
        }
      }
    }

    stage('Publish site') {
      steps {
        // publishHTML step is provided by HTML Publisher plugin
        publishHTML([
          allowMissing: false,
          alwaysLinkToLastBuild: true,
          keepAll: true,
          reportDir: 'site',
          reportFiles: 'index.html',
          reportName: 'Karunya University - Simple Site'
        ])
      }
    }
  }

  post {
    always {
      archiveArtifacts artifacts: 'site/**', fingerprint: true
    }
  }
}


Save the job.
7) Run the pipeline

Click Build Now on the pipeline job page.

Open the build (click the build number under Build History).

On the left side, you should now see a link Karunya University - Simple Site (this is the HTML Publisher view). Click it to see the generated static site rendered inside Jenkins.

Also you can download archived artifacts: Archived artifacts → site/** → download index.html.

8) Alternate: Put Jenkinsfile in a Git repo and use Pipeline from SCM

If you prefer source-controlled pipeline:

Create a repo:

git init my-site-pipeline
cd my-site-pipeline
# create Jenkinsfile with the exact pipeline script above
git add Jenkinsfile
git commit -m "Add Jenkinsfile pipeline to generate static site"
# push to GitHub or local git server


In Jenkins job configuration:

Definition: choose Pipeline script from SCM.

Select Git, add repo URL and credentials, set branch, and path to Jenkinsfile. Save and Build Now.

9) Useful commands and checks

View container status:

docker ps --filter name=jenkins


View logs:

docker logs -f jenkins


If you need to exec into container:

docker exec -it jenkins /bin/bash
# inspect /var/jenkins_home

10) Troubleshooting & tips

Cannot access Docker socket: You might get permission errors when Jenkins tries to run Docker. Either:

Ensure the host user that runs Docker is part of docker group (on host), or

Adjust socket permissions (not recommended), or

Run Jenkins container with user mapping — advanced topic.

Plugin step not found: If publishHTML step fails, confirm HTML Publisher is installed and Jenkins restarted.

Ports in use: If 8080 is busy, change ports mapping to e.g. "8081:8080".

Jenkins takes long first start: first boot installs lots of things — wait ~2–5 minutes depending on internet/host.

Date format in Groovy: ${new Date().format('yyyy')} prints the year; if there’s an error, try using def year = new Date().format('yyyy') in script and use year.

11) Security & production notes

Mounting /var/run/docker.sock is convenient but gives Jenkins root-level power to the host. For production use consider:

Using a dedicated Docker host or DinD (Docker-in-Docker) with constrained permissions.

Running Jenkins agents (build executors) on separate worker machines/nodes.

Use credentials store for secrets and avoid writing secrets in Jenkinsfile.

Backup /var/jenkins_home volume regularly.

12) Cleanup (if needed)

Stop & remove:

docker compose down --volumes


This removes the jenkins_home volume (so keep backups if you need Jenkins data).

If you want, I can:

produce a ready-to-run Jenkinsfile and docker-compose.yml in a Git repo and give exact git commands to push it, or

provide a scripted way to auto-install the HTML Publisher plugin using Jenkins CLI (if you want automation rather than manual plugin install).
✅ How to get Jenkins Initial Admin Password
✔️ Step 1 — Make sure Jenkins container is running

Run:

docker ps


You should see a container named jenkins.
If not running, start it:

docker compose up -d

✔️ Step 2 — Run this command to print the password
Linux / macOS / WSL
docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword

Windows CMD
docker exec jenkins cat \var\jenkins_home\secrets\initialAdminPassword

Windows PowerShell
docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword


PowerShell uses / — not \.

✔️ After running the command

You will see a long string like:

f3c8b1a41e2f4e1c9d39e6e1d74c59e3


👉 Copy that and paste it in Jenkins unlock screen
http://localhost:8080

⚠️ If you get an error like "No such file or directory"

Run:

docker exec -it jenkins ls /var/jenkins_home/secrets


You should see the file:

initialAdminPassword


If it is not there, Jenkins might still be starting.
Wait 1–2 minutes and try again.

⚠️ If container name is not "jenkins"

Run:

docker ps


Find the actual container name or ID (example: jenkins_jenkins_1).

Then run:

docker exec <container_name> cat /var/jenkins_home/secrets/initialAdminPassword


Example:

docker exec jenkins_jenkins_1 cat /var/jenkins_home/secrets/initialAdminPa
